version: "2"

build:
  os: "ubuntu-22.04"
  apt_packages:
    - mpich
    - libmpich-dev

  tools:
    python: "3.10"
  jobs:
    pre_install:
      - pip install -r docs/requirements.txt
sphinx:
  configuration: docs/source/conf.py

