version: "2"

build:
  os: "ubuntu-22.04"
  apt_packages:
    - mpich
    - libmpich-dev

  tools:
    python: "3.10"
  jobs:
    pre_install:
      - pip install numpy cython cftime pytest twine wheel check-manifest

sphinx:
  configuration: docs/source/conf.py

