version: "2"

build:
  os: "ubuntu-22.04"
  apt_packages:
    - mpich
    - libmpich-dev


  tools:
    python: "3.10"
  jobs:
    pre_install:

      # - export PNETCDF_VERSION="1.12.3"
      # - export $READTHEDOCS_OUTPUT/PnetCDF=$READTHEDOCS_OUTPUT/PnetCDF
      # - export CC=mpicc.mpich
      - echo "Download and build PnetCDF version $PNETCDF_VER"
      - echo $READTHEDOCS_OUTPUT
      - wget https://parallel-netcdf.github.io/Release/pnetcdf-$PNETCDF_VER.tar.gz
      - tar -xzf pnetcdf-$PNETCDF_VER.tar.gz
      - cd ./pnetcdf-$PNETCDF_VER; ./configure --prefix $READTHEDOCS_OUTPUT/PnetCDF --enable-shared --enable-debug --disable-fortran --disable-cxx; make -j 8; make install
      - pip install numpy cython cftime pytest twine wheel check-manifest mpi4py
      

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
    


sphinx:
  configuration: docs/source/conf.py