version: "2"

build:
  os: "ubuntu-22.04"
  apt_packages:
    - mpich
    - libmpich-dev
    - libhdf5-mpich-dev 

  tools:
    python: "3.10"
  jobs:
    pre_install:
      # - curl -u ${USERNAME}:${PASSWORD} https://httpbin.org/basic-auth/username/password
      # - export PNETCDF_VERSION="1.12.3"
      # - export $READTHEDOCS_OUTPUT/PnetCDF=$READTHEDOCS_OUTPUT/PnetCDF
      - export CC=mpicc.mpich
      - echo "Download and build PnetCDF version 1.12.3"
      - wget https://parallel-netcdf.github.io/Release/pnetcdf-1.12.3.tar.gz
      - tar -xzf pnetcdf-1.12.3.tar.gz
      - pushd pnetcdf-1.12.3
      - ./configure --prefix $$READTHEDOCS_OUTPUT/PnetCDF --enable-shared --enable-debug --disable-fortran --disable-cxx 
      - make -j 8
      - make install
      - export PATH=$$READTHEDOCS_OUTPUT/PnetCDF/bin:$PATH 
      - popd
      - python -m pip install --upgrade pip
      - pip install numpy cython cftime pytest twine wheel check-manifest mpi4py

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py